# SPDX-FileCopyrightText: 2023 Carnegie Mellon University
# SPDX-License-Identifier: 0BSD

exclude: '^(.*_pb2.pyi?|src/hawk/scout/trainer/yolo.*/yolov5.*/.*)$'

repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.2
    hooks:
      - id: pyupgrade
        name: Modernize python code
        args: ["--py38-plus"]

  - repo: https://github.com/asottile/yesqa
    rev: v1.4.0
    hooks:
      - id: yesqa
        additional_dependencies: &flake_deps
          - flake8-bugbear

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: Reorder python imports with isort

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        name: Format python code with black
        language_version: python3

  - repo: https://github.com/asottile/blacken-docs
    rev: 1.13.0
    hooks:
      - id: blacken-docs
        name: Format python code in documentation

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        name: Lint python code with flake8
        additional_dependencies: *flake_deps

#  - repo: https://github.com/pre-commit/mirrors-mypy
#    rev: v1.2.0
#    hooks:
#      - id: mypy
#        name: Check type hints with mypy
#        pass_filenames: false
#        additional_dependencies:
#          - types-paramiko
#          - types-pyyaml
#          - types-tqdm

#  - repo: https://github.com/fsfe/reuse-tool
#    rev: v1.0.0
#    hooks:
#      - id: reuse
#        name: Check SPDX license tags
