{
 "title": "Hawk Mission",
 "tags": [ "hawk" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "mission_id",
    "label": "Mission ID",
    "query": {
     "query": "label_values(hawk_mission_status,mission)"
    }
   },
   {
    "name": "groundtruth",
    "label": "Class",
    "query": {
     "query": "label_values(hawk_inferenced_objects_count,gt)"
    }
   },
   {
    "name": "scouts",
    "label": "Scout",
    "query": {
     "query": "label_values(hawk_selector_priority_queue_length,instance)"
    }
   },
   {
    "name": "threshold",
    "label": "Survival threshold",
    "query": {
     "query": "label_values(hawk_inferenced_objects_bucket,le)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Current Model Version",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hawk_model_version{mission=~\"$mission_id\", instance=~\"$scouts\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average confidence",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(hawk_inferenced_objects_sum{mission=~\"$mission_id\",instance=~\"$scouts\"}) by(gt)/ sum(hawk_inferenced_objects_count{mission=~\"$mission_id\",instance=~\"$scouts\"}) by(gt)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of samples retrieved/inferenced at scout",
   "type": "timeseries",
   "description": "Number of processed samples at different points in the pipeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(hawk_retriever_retrieved_objects_total{mission=~\"$mission_id\", instance=~\"$scouts\"})",
     "legendFormat": "Retrieved objects"
    },
    {
     "expr": "sum(hawk_inferenced_objects_count{mission=~\"$mission_id\", instance=~\"$scouts\"})",
     "legendFormat": "Inferenced objects"
    }
   ]
  },
  {
   "title": "Inferenced confidence scores",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(hawk_inferenced_objects_bucket{mission=~\"$mission_id\", instance=~\"$scouts\", gt=~\"$groundtruth\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "True Positives",
   "type": "timeseries",
   "description": "Comparing True Positives encounter in the stream (ground truth) with True Positives from labeler",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(hawk_inferenced_objects_count{mission=~\"$mission_id\", gt!=\"negative\", instance=~\"$scouts\"})",
     "legendFormat": "Ground truth in stream {{mission}}"
    },
    {
     "expr": "sum(hawk_selector_dequeued_objects_count{mission=~\"$mission_id\", gt!=\"negative\", instance=~\"$scouts\"})",
     "legendFormat": "Positives sent to home {{mission}}"
    },
    {
     "expr": "sum(hawk_labeled_objects_count{mission=~\"$mission_id\"} - ignoring(le) hawk_labeled_objects_bucket{mission=~\"$mission_id\", le=\"0.0\"})",
     "legendFormat": "Positives from labeler {{mission}} (all scouts)"
    },
    {
     "expr": "sum(hawk_labeled_objects_count{mission=~\"$mission_id\"} - ignoring(le) hawk_labeled_objects_bucket{mission=~\"$mission_id\", le=\"0.0\"}) / sum(hawk_inferenced_objects_count{mission=~\"$mission_id\", gt!=\"negative\", instance=~\"$scouts\"})",
     "legendFormat": "Labeled %"
    }
   ]
  },
  {
   "title": "Sent to home confidence scores",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(hawk_selector_dequeued_objects_bucket{mission=~\"$mission_id\", instance=~\"$scouts\", gt=~\"$groundtruth\"}) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Number of samples received/labeled at home",
   "type": "timeseries",
   "description": "Number of processed samples at different points in the hawk_home pipeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(hawk_unlabeled_received_count{mission=~\"$mission_id\"})",
     "legendFormat": "Received at home"
    },
    {
     "expr": "hawk_labeled_objects_count{mission=~\"$mission_id\"}",
     "legendFormat": "Labeled by labeler"
    }
   ]
  },
  {
   "title": "Queue lengths",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "hawk_retriever_queue_length{mission=~\"$mission_id\", instance=~\"$scouts\"}",
     "legendFormat": "Retriever queue {{instance}}"
    },
    {
     "expr": "hawk_selector_priority_queue_length{mission=~\"$mission_id\", instance=~\"$scouts\"}",
     "legendFormat": "Selector priority queue {{instance}}"
    },
    {
     "expr": "hawk_selector_result_queue_length{mission=~\"$mission_id\", instance=~\"$scouts\"}",
     "legendFormat": "Selector result queue {{instance}}"
    },
    {
     "expr": "hawk_unlabeled_queue_length{mission=~\"$mission_id\"}",
     "legendFormat": "Unlabeled priority queue"
    },
    {
     "expr": "hawk_labeler_queued_length{mission=~\"$mission_id\"}",
     "legendFormat": "Labeler queue"
    },
    {
     "expr": "hawk_labeled_queue_length{mission=~\"$mission_id\", instance=~\"$scouts\"}",
     "legendFormat": "Labeled queue {{scout}}"
    }
   ]
  },
  {
   "title": "Survival metrics (hawk_inferenced_objects metrics)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum(hawk_inferenced_objects_count{mission=~\"$mission_id\", instance=~\"$scouts\", gt!=\"negative\"} - ignoring(le) hawk_inferenced_objects_bucket{mission=~\"$mission_id\", instance=~\"$scouts\", gt!=\"negative\", le=\"$threshold\"})",
     "legendFormat": "SurvTP"
    },
    {
     "expr": "sum(hawk_inferenced_objects_bucket{mission=~\"$mission_id\", instance=~\"$scouts\", gt!=\"negative\", le=\"$threshold\"})",
     "legendFormat": "SurvFN"
    },
    {
     "expr": "sum(hawk_inferenced_objects_count{mission=~\"$mission_id\", instance=~\"$scouts\", gt=\"negative\"} - ignoring(le) \nhawk_inferenced_objects_bucket{mission=~\"$mission_id\", instance=~\"$scouts\", gt=\"negative\", le=\"$threshold\"})",
     "legendFormat": "SurvFP"
    }
   ]
  }
 ]
}