"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    FileDescriptor as google___protobuf___descriptor___FileDescriptor,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Optional as typing___Optional,
    Text as typing___Text,
    overload as typing___overload,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int


DESCRIPTOR: google___protobuf___descriptor___FileDescriptor = ...

class ObjectId(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    oid: typing___Text = ...

    def __init__(self,
        *,
        oid : typing___Optional[typing___Text] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"oid",b"oid"]) -> None: ...
type___ObjectId = ObjectId

class HawkObject(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    media_type: typing___Text = ...
    content: builtin___bytes = ...

    def __init__(self,
        *,
        media_type : typing___Optional[typing___Text] = None,
        content : typing___Optional[builtin___bytes] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"content",b"content",u"media_type",b"media_type"]) -> None: ...
type___HawkObject = HawkObject

class Region(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    center_x: builtin___float = ...
    center_y: builtin___float = ...
    width: builtin___float = ...
    height: builtin___float = ...

    def __init__(self,
        *,
        center_x : typing___Optional[builtin___float] = None,
        center_y : typing___Optional[builtin___float] = None,
        width : typing___Optional[builtin___float] = None,
        height : typing___Optional[builtin___float] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"center_x",b"center_x",u"center_y",b"center_y",u"height",b"height",u"width",b"width"]) -> None: ...
type___Region = Region

class Detection(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    class_name: typing___Text = ...
    confidence: builtin___float = ...

    @property
    def coords(self) -> type___Region: ...

    def __init__(self,
        *,
        class_name : typing___Optional[typing___Text] = None,
        confidence : typing___Optional[builtin___float] = None,
        coords : typing___Optional[type___Region] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"_confidence",b"_confidence",u"_coords",b"_coords",u"confidence",b"confidence",u"coords",b"coords"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"_confidence",b"_confidence",u"_coords",b"_coords",u"class_name",b"class_name",u"confidence",b"confidence",u"coords",b"coords"]) -> None: ...
    @typing___overload
    def WhichOneof(self, oneof_group: typing_extensions___Literal[u"_confidence",b"_confidence"]) -> typing_extensions___Literal["confidence"]: ...
    @typing___overload
    def WhichOneof(self, oneof_group: typing_extensions___Literal[u"_coords",b"_coords"]) -> typing_extensions___Literal["coords"]: ...
type___Detection = Detection
