# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\x12\x0f\x65\x64u.cmu.cs.hawk\"\x17\n\x08ObjectId\x12\x0b\n\x03oid\x18\x01 \x01(\t\"1\n\nHawkObject\x12\x12\n\nmedia_type\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\x0c\"K\n\x06Region\x12\x10\n\x08\x63\x65nter_x\x18\x01 \x01(\x02\x12\x10\n\x08\x63\x65nter_y\x18\x02 \x01(\x02\x12\r\n\x05width\x18\x03 \x01(\x02\x12\x0e\n\x06height\x18\x04 \x01(\x02\"\x80\x01\n\tDetection\x12\x12\n\nclass_name\x18\x01 \x01(\t\x12\x17\n\nconfidence\x18\x02 \x01(\x02H\x00\x88\x01\x01\x12,\n\x06\x63oords\x18\x03 \x01(\x0b\x32\x17.edu.cmu.cs.hawk.RegionH\x01\x88\x01\x01\x42\r\n\x0b_confidenceB\t\n\x07_coordsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OBJECTID']._serialized_start=33
  _globals['_OBJECTID']._serialized_end=56
  _globals['_HAWKOBJECT']._serialized_start=58
  _globals['_HAWKOBJECT']._serialized_end=107
  _globals['_REGION']._serialized_start=109
  _globals['_REGION']._serialized_end=184
  _globals['_DETECTION']._serialized_start=187
  _globals['_DETECTION']._serialized_end=315
# @@protoc_insertion_point(module_scope)
